version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command:  npm start
    ports:
      - 3000:3000
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command:  npm run serve
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
volumes:
  postgres_data: 

